#!/usr/bin/env bash

exec sed -i "s/APP_URL=.*/APP_URL=${APP_URL}/" .env
exec echo 'yes' | php artisan migrate
exec echo 'yes' | php artisan db:seed --class PermissionSeeder
exec php artisan serve --host=0.0.0.0 --port=80
